### ISSUE TITLE
missing type?

### ISSUE THREAD

**Issue by teuben** [SoftwareUnderstanding/software_types#19]
We have a new image visualization application which I can't quite fit in the categories that I see here. It's basically run like a notebook, i.e. from the command line you can say  "carta myfile.fits", but I''ve also see it being launched from archive wbesited where they have some info on an astronomical object, and it then launches carta.

See cartavis.org if you want to see it in action.

Arguably we could rename NotebookApplication to WebApplication?

In terms of examples for SoftwarePackage type, are linux "snap" or "flatpack" examples of this? They kind of fit two categories.

**Comment by dgarijo** [comment]
We could add a category called WebApplication. And then it can be both a notebook and a Web application.

You can fit something in more than one category.

@proycon thoughts?

**Comment by proycon** [comment]
> We could add a category called WebApplication. And then it can be both a notebook and a Web application.

No, WebApplication already exists in schema.org . No need for us to redefine it. Our NotebookApplication is in fact a subclass of `schema:WebApplication`

> You can fit something in more than one category.

Indeed,

> It's basically run like a notebook, i.e. from the command line you can say "carta myfile.fits", but I''ve also see it being launched from archive wbesited where they have some info on an astronomical object, and it then launches carta.

I checked cartavis.org and it looks like schema:WebApplication and sofwaretypes:DesktopApplication are the best fits in this case. It's basically a web application and a desktop variant is also offered (via electron it seems, which is basically just a browser in a box). I don't think NotebookApplication is a good enough fit.

Maybe part of the confusion was caused because we don't explicitly list the existing schema.org types in our README (like WebApplication or MobileApplication), which are all valid values.

**Comment by proycon** [comment]
I hope the above commit 4086edc addresses this confusion sufficiently.

I also see I forgot to answer one of @teuben's questions:

> In terms of examples for SoftwarePackage type, are linux "snap" or "flatpack" examples of this? They kind of fit two categories.

They indeed kind of fit two of our categories, SoftwarePackage and SoftwareImage, it's even fine to just assign both, but opting for only SoftwarePackage sounds acceptable too.

**Comment by dgarijo** [comment]
You are completely correct. Thanks!
I will review your edits and close the issue

**Comment by dgarijo** [comment]
Looks good to me. 
@teuben please reopen the issue if you think it's not properly addressed
