### ISSUE TITLE
What is the difference between terminal application and command line application?

### ISSUE THREAD

**Issue by dgarijo** [SoftwareUnderstanding/software_types#7]
Terminal application: A software application offering a terminal text-based user interface

Command line application: A software application offering a command-line interface

A terminal is a command-line interface. I am confused about this distinction and I think it should be clarified.

**Comment by proycon** [comment]
I added some extra clarification in the commit above. I kept it a bit short and will expand here:

The idea is that command line applications are applications whose primary modality of interaction is through the command line, i.e. selecting parameters, passing input and getting some output (which may in turn be redirected or piped). Tools like `grep`, `sed`, `ls` etc fall into this category. Even software like firefox (DesktopApplication) and nginx (ServerApplication) technically offer command line interfaces, but they wouldn't be classified as command line applications.

Terminal applications are those applications that offer a terminal text-based UI (aka TUI). This category may be a bit more niche (although I personally make very heavy use of them). Popular tools like vim, mutt, htop, tmux etc fall into this category.

Does this make sense? I hope the text itself is clear now, if necessary I can make it more verbose.

**Comment by dgarijo** [comment]
So these are `DesktopApplication`s then, right? The only difference is that they are use through the terminal, so you can e.g., ssh into a server without a virtual desktop. Would it make sense to make it subclass of DesktopApplication then?

**Comment by proycon** [comment]
Well, in a way perhaps, although the way I had things in mind I see `DesktopApplication` as something that demands a graphical environment / graphical display server. Something like `X11`, `wayland`, or the built-in desktops in macos (Aqua?) or windows. If we consider that the desktop then things that require that are desktop applications. I see it as synonym for a GUI interface as they typically build on some GUI toolkit, either provided natively by the platform or things like Gtk, Qt, Tk, Java swing etc...

Terminal applications are more a class apart because they don't require this 'desktop' nor a fancy graphical display server. You can indeed run them over ssh as you indicated, or plainly on the console.

**Comment by proycon** [comment]
Perhaps a special mention for one type of software: *terminal emulators* (programs like xterm, alacritty, kitty, st, iTerm2, etc...).  These would simply classify as `DesktopApplication`.

**Comment by dgarijo** [comment]
I think part of the problem may be because we are conflating an application with a graphical UI with an application that is run in a Desktop. Since terminal applications may be run from a Desktop, this may bring in confusion.

What if we rename `DesktopApplication` to `GUIApplication`? Shouldn't that make it distinguishable enough?

**Comment by proycon** [comment]
> What if we rename DesktopApplication to GUIApplication? Shouldn't that make it distinguishable enough?

I thought about that at the beginning too but It feels less consistent with the rest of the naming. If we have GUIApplication I'd expect the others to be like WUIApplication and TUIApplication and CLIApplication which gets rather messy and assumes the abbreviations are known, nor does it fit with the existing schema.org naming. There's also the existing schema:MobileApplication which also qualifies as a GUIApplication in my book.

> I think part of the problem may be because we are conflating an application with a graphical UI with an application that is run in a Desktop. Since terminal applications may be run from a Desktop, this may bring in confusion.

If you look at it in terms of what kind of environment a specific software type requires (due to the interface it offers), then I think our definitions are pretty clear:

* DesktopApplication - Requires a graphical desktop environment
* TerminalApplication - Requires a terminal (interactive tty)
* ServerApplication - Requires the ability to serve over a network
* schema:WebApplication - Requires a web-browser
* CommandLineApplication - Requires only a command line (can do without an interactive tty)
* schema:MobileApplication - Requires a mobile device

**Comment by dgarijo** [comment]
I think this narrows it then, no? Now I can understand the differences clearly. A DesktopApplication may also be a MobileApplication, as they are not disjoint. Shall I update the definitions to clarify them?

**Comment by proycon** [comment]
Sure, give it a try. They indeed don't have to be disjoint necessarily.

**Comment by dgarijo** [comment]
Yeah, it's similar to this one: `https://w3id.org/example`
```
<https://w3id.org/example> rdf:type owl:Ontology ;
                            owl:versionIRI <https://w3id.org/example/1.0.1> ;
                            <http://purl.org/dc/terms/abstract> "An example vocabulary designed to illustrate how to publish vocabularies on the Web following the FAIR principles"@en ;
                            <http://purl.org/dc/elements/1.1/description> "This is an example ontology to illustrate some of the annotations that should be included"@en ;
                            <http://purl.org/dc/elements/1.1/title> "The example ontology"@en ;
                            <http://purl.org/dc/terms/created> "February 5th, 2020"@en ;
                            <http://purl.org/dc/terms/creator> "Daniel Garijo"@en ,
                                                               "Maria Poveda-Villalon"@en ;
                            <http://purl.org/dc/terms/license> <http://creativecommons.org/licenses/by/2.0/> ;
                            <http://purl.org/vocab/vann/preferredNamespacePrefix> "exo"@en ;
                            <http://purl.org/vocab/vann/preferredNamespaceUri> "https://w3id.org/example" ;
                            <http://schema.org/citation> "Cite this vocabulary as: Garijo, D. and Poveda-Villalon, M. The example ontology 1.0.1."@en ;
                            rdfs:comment "An example vocabulary designed to illustrate how to publish vocabularies on the Web following the FAIR principles. This vocabulary describes three simple classes with 3 properties and a data property."@en ;
                            owl:backwardCompatibleWith <https://w3id.org/example/1.0.0> ;
                            owl:priorVersion <https://w3id.org/example/1.0.0> ;
                            owl:versionInfo "1.0.1"@en .
```

**Comment by dgarijo** [comment]
Done.
